openapi: 3.0.0

info:
  version: 0.0.1
  title: Connections
  description: The posts service
servers:
  - url: /connections/

tags:
  - name: Connections

paths:

  /users:
    get:
      summary: Find all users
      tags:
        - Connections
      description: Find all users
      operationId: findAllUsers
      responses:
        "200":
          description: This means is ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserRead'

  /users/{userId}:
    get:
      summary: Find user by userId
      tags:
        - Connections
      operationId: getUserByUserId
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: This means is ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRead'


  /connections:
    get:
      summary: Get all connections
      operationId: getConnections
      tags:
        - Connections
      responses:
        "200":
          description: This means is ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConnectionRead'
    post:
      summary: Add new connection
      operationId: saveConnection
      tags:
        - Connections
      requestBody:
        required: true
        description: Connections obj
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnectionWrite'
      responses:
        "200":
          description: It's ok
          content:
            text/plain:
              schema:
                type: string

  /connections/{userId}:
    get:
      summary: Get connection by userId
      operationId: getConnectionByUserName
      tags:
        - Connections
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: This means is ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConnectionRead'
components:
  schemas:
    UserRead:
      type: object
      required:
        - uuid
        - name
        - surname
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
        surname:
          type: string

    UserWrite:
      type: object
      required:
        - name
        - surname
      properties:
        name:
          type: string
        surname:
          type: string

    ConnectionRead:
      type: object
      required:
        - uuid
        - follower
        - followed
      properties:
        uuid:
          type: string
          format: uuid
        follower:
          type: integer
        followed:
          type: integer

    ConnectionWrite:
      type: object
      required:
        - follower
        - followed
      properties:
        follower:
          type: integer
        followed:
          type: integer