openapi: 3.0.0

info:
  version: 0.0.1
  title: Connections
  description: The posts service
servers:
  - url: /connections/

tags:
  - name: Connections

paths:

  /users:
    get:
      summary: Find all users
      tags:
        - Users
      description: Find all users
      operationId: findAllUsers
      responses:
        "200":
          description: This means is ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: add new user
      description: add new user
      tags:
        - Users
      operationId: addNewUser
      requestBody:
        required: true
        description: User obj
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "200":
          description: It's ok
          content:
            text/plain:
              schema:
                type: string


  /users/{userId}:
    get:
      summary: Find user by userId
      tags:
        - Users
      operationId: getUserByUserId
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: This means is ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      summary: Edit user by userId
      operationId: updateUserById
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        description: User obj
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "200":
          description: This means is ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /connections:
    get:
      summary: Get all connections
      operationId: getConnections
      tags:
        - Connections
      responses:
        "200":
          description: This means is ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Connection'
    post:
      summary: Add new connection
      operationId: saveConnection
      tags:
        - Connections
      requestBody:
        required: true
        description: Connections obj
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Connection'
      responses:
        "200":
          description: It's ok
          content:
            text/plain:
              schema:
                type: string

  /connections/{userId}:
    get:
      summary: Get connection by userId
      operationId: getConnectionByUserName
      tags:
        - Connections
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: This means is ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Connection'
    put:
      summary: Update new connection
      operationId: update Connection
      tags:
        - Connections
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        description: Connections obj
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Connection'
      responses:
        "200":
          description: It's ok
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:

    User:
      type: object
      required:
        - uuid
        - name
        - surname
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
        surname:
          type: string

    Connection:
      type: object
      required:
        - uuid
        - follower
        - followed
      properties:
        uuid:
          type: string
          format: uuid
        follower:
          type: integer
        followed:
          type: integer