CREATE TABLE USERS
(
    id      UUID UNIQUE PRIMARY KEY,
    name    VARCHAR NOT NULL,
    surname VARCHAR NOT NULL
);

CREATE TABLE CONNECTIONS
(
    id       UUID UNIQUE PRIMARY KEY,
    follower UUID NOT NULL,
    followed UUID NOT NULL
);